[phases.setup]
aptPkgs = [
  "python3",
  "make",
  "gcc",
  "g++",
  "nodejs",
  "npm",
  "php-cli",
  "php-zip",
  "php-mbstring",
  "php-pdo",
  "php-mysql"
]

cmds = [
  "a2enmod rewrite",
]

[phases.build]
cmds = [
  "npm ci --prefix frontend",
  "npm run build --prefix frontend",
  "composer install --no-dev --optimize-autoloader",
]

[start]
cmd = "php -S 0.0.0.0:$PORT -t frontend/dist rw-entrypoint.php"
